CREATE DATABASE lab CHARACTER SET utf8 COLLATE utf8_polish_ci;

CREATE TABLE PRODUKT(
    ID_PRODUKTU int(8) NOT NULL,
    NAZWA varchar(15) NOT NULL,
    CENA int(5) NOT NULL,
    PRACOWNIK varchar(40) NOT NULL,
    KATEGORIA char(8) NOT NULL,
    PRIMARY KEY(ID_PRODUKTU),
    INDEX(KATEGORIA)
);

CREATE TABLE KLIENT(
    ID_KLIENTA int(6) NOT NULL,
    IMIE varchar(20) NOT NULL,
    NAZWISKO varchar(40) NOT NULL,
    ADRES varchar(60) NULL,
    PRIMARY KEY(ID_KLIENTA)
);

CREATE TABLE ZAMOWIENIE(
    NR_ZAMOWIENIA int(8) NOT NULL,
    ID_KLIENTA int(6) NOT NULL,
    STATUS enum('ZLOZONE', 'W REALIZACJI', 'OPLACONE', 'ZREALIZOWANE') NOT NULL,
    TYP_DOSTAWY char(8) NOT NULL,
    WARTOSC double(8,2) NOT NULL,
    PRIMARY KEY(NR_ZAMOWIENIA),
    INDEX(ID_KLIENTA)
);

CREATE TABLE POZYCJA_ZAMOWIENIA(
    ID_PRODUKTU int(8) NOT NULL,
    NR_ZAMOWIENIA int(8) NOT NULL,
    LICZBA_SZTUK int(4) NOT NULL,
    RABAT int(2) NOT NULL,
    PRIMARY KEY(ID_PRODUKTU, NR_ZAMOWIENIA)
);

CREATE TABLE KATEGORIA_PRODUKTU(
    KATEGORIA char(8) NOT NULL PRIMARY KEY
);
 
ALTER TABLE produkt MODIFY CENA double(5,2) NOT NULL;
 
ALTER TABLE produkt DROP COLUMN PRACOWNIK;
 
ALTER TABLE produkt ADD OPIS text(50) NOT NULL AFTER CENA;
 
ALTER TABLE produkt ADD LICZBA_SZTUK int(4) NOT NULL;
 
ALTER TABLE produkt ADD FOREIGN KEY(KATEGORIA) REFERENCES kategoria_produktu(KATEGORIA);

ALTER TABLE klient MODIFY NAZWISKO varchar(20) NOT NULL;

ALTER TABLE klient MODIFY ADRES varchar(60) NOT NULL;

ALTER TABLE zamowienie ADD RABAT int(2) NULL;

ALTER TABLE zamowienie ADD DATA date NOT NULL AFTER ID_KLIENTA;

ALTER TABLE zamowienie ADD FOREIGN KEY(ID_KLIENTA) REFERENCES klient(ID_KLIENTA);

ALTER TABLE pozycja_zamowienia ADD FOREIGN KEY(ID_PRODUKTU) REFERENCES produkt(ID_PRODUKTU);

ALTER TABLE pozycja_zamowienia ADD FOREIGN KEY(NR_ZAMOWIENIA) REFERENCES zamowienie(NR_ZAMOWIENIA);

ALTER TABLE pozycja_zamowienia DROP COLUMN RABAT;

ALTER TABLE kategoria_produktu ADD OPIS text(50) NOT NULL;

DROP TABLE pozycja_zamowienia;
DROP TABLE zamowienie;
DROP TABLE produkt;
DROP TABLE klient;
DROP TABLE kategoria_produktu;

DROP DATABASE lab;